package lv.zesloka.skani.presentation.model.text

enum class AppStringId {
    ERR_MSG_UNKNOWN_ERROR,
    ERR_MSG_USERNAME_TOO_SHORT,
    ERR_MSG_USERNAME_TOO_LONG,
    ERR_MSG_PASSWORD_EMPTY,
    ERR_MSG_EMAIL_INVALID,
    ERR_MSG_INVALID_SIGN_UP_INPUT,
    ERR_MSG_INVALID_EMAIL_VERIFY_CODE,
    TITLE_SIGN_UP,
    LABEL_ACTION_POSITIVE,
    TITLE_LOGIN,
    ERR_MSG_WRONG_USERNAME_OR_PASSWORD,
    TEXT_INITIALIZE,
    TEXT_USER_LODGED_IN,
    TEXT_USER_NOT_LODGED_IN,
    ERR_MSG_ERROR_HAPPENED,
    ERROR,
    GENERIC_ERROR


}